// Generated by scripts/sync-plugin-catalog.ts. Do not edit by hand.
export const catalog = {
  "version": 1,
  "plugins": [
    {
      "id": "native-rust-demo",
      "name": "Native Rust Demo",
      "version": "0.1.0",
      "publisher": "krusty.examples",
      "package": "npm:@krusty/native-rust-demo",
      "description": "Reference package for hot-reloadable native Rust TUI plugins.",
      "runtime": "native",
      "tags": [
        "example",
        "native",
        "hot-reload",
        "tui"
      ],
      "homepage": "https://github.com/honeycomb-Technologies/Mitsuro/tree/main/examples/plugins/native-rust",
      "repository": "https://github.com/honeycomb-Technologies/Mitsuro",
      "official": true
    },
    {
      "id": "js-ts-demo",
      "name": "JS/TS Demo",
      "version": "0.1.0",
      "publisher": "krusty.examples",
      "package": "npm:@krusty/js-ts-demo",
      "description": "Reference package for TypeScript TUI plugins executed through edon/libnode.",
      "runtime": "js",
      "tags": [
        "example",
        "typescript",
        "edon",
        "libnode",
        "tui"
      ],
      "homepage": "https://github.com/honeycomb-Technologies/Mitsuro/tree/main/examples/plugins/js-ts",
      "repository": "https://github.com/honeycomb-Technologies/Mitsuro",
      "official": true
    }
  ]
} as const;
