use std::sync::Arc;

use serde_json::json;
use tracing::{debug, info, warn};
use uuid::Uuid;

use crate::agent::subagent::{
    build_context::SharedBuildContext, AgentProgress, AgentProgressStatus,
    DelegatedProcessArtifact, SubAgentPool, SubAgentTask,
};
use crate::agent::DelegatedRunStage;
use crate::storage::{
    Database, DelegatedRunRole, DelegatedRunScope, DelegatedRunStartInput, DelegatedRunStore,
    ProjectSettings,
};
use crate::tools::registry::DelegationPolicy;
use crate::tools::{ToolContext, ToolResult};

use super::{
    background_started_result, build_confidence, build_coverage_gap_notice,
    build_investigation_summary, classify_build_outcome, open_delegated_run_store, AgentTool,
    Params,
};

fn deduplicate_background_processes(processes: &mut Vec<DelegatedProcessArtifact>) {
    processes.sort_by(|left, right| left.process_id.cmp(&right.process_id));
    processes.dedup_by(|left, right| left.process_id == right.process_id);
}

async fn revalidate_background_processes(
    processes: &mut [DelegatedProcessArtifact],
    registry: Option<&crate::process::ProcessRegistry>,
    process_owner_id: Option<&str>,
) {
    let Some(registry) = registry else {
        // A captured startup result is not sufficient proof at finalization if
        // the inherited registry is unavailable. Keep the artifact for audit,
        // but make sure it cannot be classified as an active handoff.
        for process in processes {
            process.status = "unverified".to_string();
        }
        return;
    };

    for process in processes {
        let current = match process_owner_id {
            Some(owner_id) => registry.get_for_user(owner_id, &process.process_id).await,
            // Single-tenant callers use the registry's default owner. Process
            // IDs are generated by the registry and originate in this result.
            None => registry.get(&process.process_id).await,
        };
        process.status = current
            .as_ref()
            .map(|info| info.display_status().to_string())
            .unwrap_or_else(|| "missing".to_string());
    }
}

fn active_process_handoff_summary(processes: &[DelegatedProcessArtifact]) -> Option<String> {
    let active = processes
        .iter()
        .filter(|process| {
            matches!(process.status.as_str(), "running" | "suspended")
                && !process.endpoint_hints.is_empty()
        })
        .collect::<Vec<_>>();
    if active.is_empty() {
        return None;
    }

    Some(
        active
            .iter()
            .map(|process| {
                let endpoints = if process.endpoint_hints.is_empty() {
                    String::new()
                } else {
                    format!(" at {}", process.endpoint_hints.join(", "))
                };
                format!("{} ({}){}", process.process_id, process.status, endpoints)
            })
            .collect::<Vec<_>>()
            .join("; "),
    )
}

fn classify_build_outcome_with_handoff(
    results_len: usize,
    failed_builders: usize,
    modified_files: usize,
    has_active_process_handoff: bool,
) -> &'static str {
    if modified_files > 0 {
        return classify_build_outcome(results_len, failed_builders, modified_files);
    }
    if results_len > 0 && failed_builders == 0 && has_active_process_handoff {
        return "success";
    }
    classify_build_outcome(results_len, failed_builders, modified_files)
}

fn build_confidence_with_handoff(
    failed_builders: usize,
    modified_files: usize,
    has_active_process_handoff: bool,
) -> &'static str {
    if modified_files > 0 {
        return build_confidence(failed_builders, modified_files);
    }
    if failed_builders == 0 && has_active_process_handoff {
        // Registry liveness proves that the process is controllable, but an
        // endpoint hint parsed from its command is not a readiness probe.
        return "medium";
    }
    build_confidence(failed_builders, modified_files)
}

fn build_summary_with_handoff(
    successful_builders: usize,
    failed_builders: usize,
    modified_files: usize,
    lines_added: usize,
    lines_removed: usize,
    process_handoff: Option<&str>,
) -> String {
    let build_summary = build_investigation_summary(
        successful_builders,
        failed_builders,
        modified_files,
        lines_added,
        lines_removed,
    );

    match (modified_files > 0, process_handoff) {
        (true, Some(handoff)) => format!(
            "{build_summary} Delegated build also handed off tracked process(es): {handoff}. Process liveness was revalidated at aggregation; endpoint readiness remains unverified."
        ),
        (false, Some(handoff)) => format!(
            "Delegated build handed off tracked process(es): {handoff}. Process liveness was revalidated at aggregation; endpoint readiness remains unverified."
        ),
        (_, None) => build_summary,
    }
}

impl AgentTool {
    // Build
    // -----------------------------------------------------------------------

    pub(super) async fn execute_build(&self, params: Params, ctx: &ToolContext) -> ToolResult {
        if ctx.project_dir.is_none() {
            return ToolResult::error(
                "No project directory is selected for this session. Create or choose a project directory, then promote the session before using build.",
            );
        }

        let client = self.resolve_client(ctx);

        // Create shared build context
        let context = Arc::new(SharedBuildContext::new());

        // Merge conventions: project settings as base, user params override/extend
        let project_settings = ctx
            .project_dir
            .as_ref()
            .map(|p| ProjectSettings::load(p))
            .unwrap_or_default();
        let mut conventions = project_settings.conventions.unwrap_or_default();
        if let Some(user_conventions) = &params.conventions {
            conventions.extend(user_conventions.iter().cloned());
        }
        if !conventions.is_empty() {
            context.set_conventions(conventions);
        }

        // Smart concurrency default: match component count, clamped to reasonable range
        let num_components = params.components.as_ref().map(|c| c.len()).unwrap_or(1);
        let concurrency = params.max_concurrency.unwrap_or_else(|| {
            // Default: match component count, capped at reasonable limit
            num_components.clamp(2, 10)
        });

        // Build tasks - all use Opus for high-quality code generation
        let mut tasks: Vec<SubAgentTask> = Vec::new();
        let delegated_run_id = Uuid::new_v4().to_string();
        let delegation_policy =
            DelegationPolicy::for_subagent_build(ctx.permission_mode, ctx.subagent_max_turns);
        let delegated_store = open_delegated_run_store(ctx);
        let mut target_scope = Vec::new();

        if let Some(ref components) = params.components {
            let total = components.len();
            let other_components: Vec<_> = components.iter().map(|c| c.as_str()).collect();

            // One agent per component - each gets their own file for TRUE parallelism
            for (i, component) in components.iter().enumerate() {
                let name = component.split_whitespace().next().unwrap_or("builder");
                let others: Vec<_> = other_components
                    .iter()
                    .enumerate()
                    .filter(|(j, _)| *j != i)
                    .map(|(j, c)| format!("  - Builder {}: {}", j, c))
                    .collect();

                // Create detailed prompt emphasizing SEPARATE FILES
                let task_prompt = format!(
                    "You are Builder {} of {} in a parallel build team.\n\n\
                     YOUR COMPONENT: {}\n\n\
                     OVERALL GOAL:\n{}\n\n\
                     OTHER BUILDERS (working in parallel):\n{}\n\n\
                     PARALLEL BUILD STRATEGY:\n\
                     1. Create YOUR OWN file(s) for your component - don't wait for others\n\
                     2. Name files clearly: {}_something.ext (e.g., game_engine.py, snake_logic.py)\n\
                     3. If you need to import from another builder's module, assume it exists\n\
                     4. Export clear interfaces (functions, classes) others can import\n\
                     5. At the end, if a main.py/main.rs is needed, Builder 0 creates it and imports all modules\n\n\
                     COORDINATION:\n\
                     - Check [SHARED TYPES] for interfaces other builders registered\n\
                     - Register YOUR public functions/classes so others can import them\n\
                     - File locks are automatic - but you shouldn't need them if using separate files\n\n\
                     BUILD YOUR COMPONENT NOW. Create your file(s) and implement fully.",
                    i, total,
                    component,
                    params.prompt,
                    if others.is_empty() { "  (none - you're solo)".to_string() } else { others.join("\n") },
                    name.to_lowercase().replace(' ', "_")
                );

                let mut task = SubAgentTask::new(format!("builder-{}", i), task_prompt)
                    .with_name(name)
                    .with_working_dir(ctx.working_dir.clone())
                    .with_delegated_run_id(delegated_run_id.clone())
                    .with_delegation_policy(delegation_policy.clone())
                    .with_process_context(
                        ctx.process_registry.clone(),
                        ctx.user_id.clone(),
                        ctx.session_id.clone(),
                    );
                if let Some(sandbox_root) = ctx.sandbox_root.clone() {
                    task = task.with_sandbox_root(sandbox_root);
                }
                if let Some(max_turns) = ctx.subagent_max_turns {
                    task = task.with_max_turns(max_turns);
                }

                // Attach plan task ID if provided for auto-completion
                if let Some(ref task_ids) = params.task_ids {
                    if let Some(plan_task_id) = task_ids.get(i) {
                        task = task.with_plan_task_id(plan_task_id);
                    }
                }

                target_scope.push(DelegatedRunScope {
                    label: name.to_string(),
                    path: component.clone(),
                    kind: "component".to_string(),
                });
                tasks.push(task);
            }
        } else {
            // Single builder for the whole task
            target_scope.push(DelegatedRunScope {
                label: "main".to_string(),
                path: ".".to_string(),
                kind: "project".to_string(),
            });
            let mut task = SubAgentTask::new("builder-main", params.prompt.clone())
                .with_name("main")
                .with_working_dir(ctx.working_dir.clone())
                .with_delegated_run_id(delegated_run_id.clone())
                .with_delegation_policy(delegation_policy.clone())
                .with_process_context(
                    ctx.process_registry.clone(),
                    ctx.user_id.clone(),
                    ctx.session_id.clone(),
                );
            if let Some(sandbox_root) = ctx.sandbox_root.clone() {
                task = task.with_sandbox_root(sandbox_root);
            }
            if let Some(max_turns) = ctx.subagent_max_turns {
                task = task.with_max_turns(max_turns);
            }
            tasks.push(task);
        }

        if let (Some(store), Some(session_id)) = (delegated_store.as_ref(), ctx.session_id.as_ref())
        {
            if let Err(err) = store.create_run(&DelegatedRunStartInput {
                delegated_run_id: delegated_run_id.clone(),
                parent_session_id: session_id.clone(),
                parent_tool_call_id: ctx.tool_use_id.clone(),
                role: DelegatedRunRole::Build,
                stage: DelegatedRunStage::Created,
                provider: Some(client.provider_id().to_string()),
                model: Some(client.config().model.clone()),
                resumable: true,
                resumed_from_run_id: None,
                target_scope,
            }) {
                warn!(delegated_run_id = %delegated_run_id, error = %err, "Failed to persist delegated build run start");
            }
        }

        info!("Agent tool (build): Created {} builder tasks", tasks.len());
        for (i, task) in tasks.iter().enumerate() {
            debug!("Builder {}: id={}, name={}", i, task.id, task.name);
        }

        // Create pool and execute with build context
        let pool = SubAgentPool::new(client, self.cancellation.clone())
            .with_concurrency(concurrency)
            .with_override_model(ctx.current_model.clone());

        info!(
            "Agent tool (build): Starting builder pool with max_concurrency={} (components={}), background={}",
            concurrency, num_components, params.run_in_background.unwrap_or(false)
        );

        // ── Background mode ──────────────────────────────────────────
        if params.run_in_background.unwrap_or(false) {
            let bg_delegated_run_id = delegated_run_id.clone();
            let bg_db_path = ctx.db_path.clone();
            let bg_delegation_policy = delegation_policy.clone();
            let bg_process_registry = ctx.process_registry.clone();
            let bg_process_owner_id = ctx.user_id.clone();
            let progress_tx = ctx.agent_progress_tx.clone();

            tokio::spawn(async move {
                // Keep a clone for the completion event after execute_builders consumes the tx
                let completion_tx = progress_tx.clone();

                let mut results = if let Some(progress_tx) = progress_tx {
                    pool.execute_builders(tasks, context.clone(), progress_tx)
                        .await
                } else {
                    let (tx, _rx) = tokio::sync::mpsc::unbounded_channel();
                    pool.execute_builders(tasks, context.clone(), tx).await
                };

                for result in &mut results {
                    revalidate_background_processes(
                        &mut result.background_processes,
                        bg_process_registry.as_deref(),
                        bg_process_owner_id.as_deref(),
                    )
                    .await;
                }

                // Build the finalization payload (same logic as synchronous path)
                let stats = context.stats();
                let mut all_files: Vec<String> = Vec::new();
                let mut total_turns = 0;
                let mut total_duration_ms = 0u64;
                let mut errors: Vec<String> = Vec::new();
                let mut builders = Vec::new();
                let mut background_processes = Vec::new();

                for result in &results {
                    builders.push(result.evidence_json());
                    background_processes.extend(result.background_processes.iter().cloned());
                    if let Some(err) = &result.error {
                        errors.push(format!("{}: {}", result.task_id, err));
                    }
                    all_files.extend(result.files_examined.clone());
                    total_turns += result.turns_used;
                    total_duration_ms += result.duration_ms;
                }
                deduplicate_background_processes(&mut background_processes);

                let mut unique_files = Vec::new();
                for file in all_files {
                    if !unique_files.iter().any(|existing| existing == &file) {
                        unique_files.push(file);
                    }
                }

                let failed_builders = errors.len();
                let successful_builders = results.len().saturating_sub(failed_builders);
                let process_handoff = active_process_handoff_summary(&background_processes);
                let outcome = classify_build_outcome_with_handoff(
                    results.len(),
                    failed_builders,
                    stats.files_modified,
                    process_handoff.is_some(),
                );
                let confidence = build_confidence_with_handoff(
                    failed_builders,
                    stats.files_modified,
                    process_handoff.is_some(),
                );
                let outcome_reason = if stats.files_modified > 0 {
                    if failed_builders == 0 {
                        "file_modifications"
                    } else {
                        "mixed"
                    }
                } else if process_handoff.is_some() && failed_builders == 0 {
                    "active_process_handoff_readiness_unverified"
                } else {
                    "no_usable_evidence"
                };
                let investigation_summary = build_summary_with_handoff(
                    successful_builders,
                    failed_builders,
                    stats.files_modified,
                    stats.lines_added,
                    stats.lines_removed,
                    process_handoff.as_deref(),
                );

                let payload = json!({
                    "delegated_run_id": bg_delegated_run_id,
                    "message": format!(
                        "Build completed: {} builders, {} turns, +{} -{} lines across {} files",
                        results.len(), total_turns, stats.lines_added, stats.lines_removed, stats.files_modified,
                    ),
                    "investigation_summary": investigation_summary,
                    "outcome": outcome,
                    "outcome_reason": outcome_reason,
                    "confidence": confidence,
                    "builder_count": results.len(),
                    "successful_agents": successful_builders,
                    "failed_agents": failed_builders,
                    "total_turns": total_turns,
                    "total_duration_ms": total_duration_ms,
                    "files_examined": unique_files,
                    "builders": builders,
                    "background_processes": background_processes,
                    "lines_added": stats.lines_added,
                    "lines_removed": stats.lines_removed,
                    "files_modified": stats.files_modified,
                    "errors": errors,
                    "delegation_policy": bg_delegation_policy.audit_json(),
                });

                if let Some(ref db_path) = bg_db_path {
                    match Database::new(db_path) {
                        Ok(db) => {
                            let store = DelegatedRunStore::new(db);
                            let final_stage = match outcome {
                                "success" => DelegatedRunStage::Complete,
                                "partial" => DelegatedRunStage::Degraded,
                                _ => DelegatedRunStage::Failed,
                            };
                            if let Err(err) = store.finalize_run(
                                &bg_delegated_run_id,
                                final_stage,
                                &payload,
                                Some(&investigation_summary),
                                failed_builders > 0,
                            ) {
                                warn!(
                                    delegated_run_id = %bg_delegated_run_id,
                                    error = %err,
                                    "Background build: failed to persist final artifact"
                                );
                            }
                        }
                        Err(e) => {
                            tracing::error!(
                                delegated_run_id = %bg_delegated_run_id,
                                error = %e,
                                "Failed to open database for background build finalization"
                            );
                        }
                    }
                }

                // Emit completion event so the parent sees the result
                if let Some(ref tx) = completion_tx {
                    let build_success = outcome == "success";
                    let status = if build_success {
                        AgentProgressStatus::Complete
                    } else {
                        AgentProgressStatus::Failed
                    };
                    if tx
                        .send(AgentProgress {
                            delegated_run_id: Some(bg_delegated_run_id.clone()),
                            task_id: "build".to_string(),
                            name: "build".to_string(),
                            status,
                            tool_count: 0,
                            tokens: 0,
                            current_action: None,
                            completion_summary: Some(investigation_summary),
                            lines_added: stats.lines_added,
                            lines_removed: stats.lines_removed,
                            completed_plan_task: None,
                        })
                        .is_err()
                    {
                        debug!("Background build progress channel disconnected (parent returned)");
                    }
                }
            });

            return background_started_result(&delegated_run_id, "build", params.name.as_deref());
        }

        // ── Synchronous mode (existing behavior) ─────────────────────

        // Execute builders with progress channel if available
        let mut results = if let Some(ref progress_tx) = ctx.agent_progress_tx {
            pool.execute_builders(tasks, context.clone(), progress_tx.clone())
                .await
        } else {
            // Fallback: create a dummy channel and discard progress
            let (tx, _rx) = tokio::sync::mpsc::unbounded_channel();
            pool.execute_builders(tasks, context.clone(), tx).await
        };

        for result in &mut results {
            revalidate_background_processes(
                &mut result.background_processes,
                ctx.process_registry.as_deref(),
                ctx.user_id.as_deref(),
            )
            .await;
        }

        info!(
            "Agent tool (build): Builder pool returned {} results",
            results.len()
        );

        // Get final stats from context
        let stats = context.stats();

        let mut all_files: Vec<String> = Vec::new();
        let mut total_turns = 0;
        let mut total_duration_ms = 0u64;
        let mut errors: Vec<String> = Vec::new();
        let mut builders = Vec::new();
        let mut background_processes = Vec::new();

        for result in &results {
            builders.push(result.evidence_json());
            background_processes.extend(result.background_processes.iter().cloned());

            if let Some(err) = &result.error {
                errors.push(format!("{}: {}", result.task_id, err));
            }

            all_files.extend(result.files_examined.clone());
            total_turns += result.turns_used;
            total_duration_ms += result.duration_ms;
        }
        deduplicate_background_processes(&mut background_processes);

        let mut unique_files = Vec::new();
        for file in all_files {
            if !unique_files.iter().any(|existing| existing == &file) {
                unique_files.push(file);
            }
        }

        let message = format!(
            "Build completed: {} builders, {} turns, +{} -{} lines across {} files",
            results.len(),
            total_turns,
            stats.lines_added,
            stats.lines_removed,
            stats.files_modified,
        );
        let failed_builders = errors.len();
        let successful_builders = results.len().saturating_sub(failed_builders);
        let process_handoff = active_process_handoff_summary(&background_processes);
        let outcome = classify_build_outcome_with_handoff(
            results.len(),
            failed_builders,
            stats.files_modified,
            process_handoff.is_some(),
        );
        let confidence = build_confidence_with_handoff(
            failed_builders,
            stats.files_modified,
            process_handoff.is_some(),
        );
        let outcome_reason = if stats.files_modified > 0 {
            if failed_builders == 0 {
                "file_modifications"
            } else {
                "mixed"
            }
        } else if process_handoff.is_some() && failed_builders == 0 {
            "active_process_handoff_readiness_unverified"
        } else {
            "no_usable_evidence"
        };
        let investigation_summary = build_summary_with_handoff(
            successful_builders,
            failed_builders,
            stats.files_modified,
            stats.lines_added,
            stats.lines_removed,
            process_handoff.as_deref(),
        );
        let coverage_gap_notice = build_coverage_gap_notice(&errors);

        let high_contention_files = stats
            .high_contention_files
            .iter()
            .map(|(path, duration)| {
                json!({
                    "file": path.display().to_string(),
                    "wait_secs": duration.as_secs_f64(),
                })
            })
            .collect::<Vec<_>>();

        let payload = json!({
            "delegated_run_id": delegated_run_id,
            "message": message,
            "investigation_summary": investigation_summary,
            "confidence": confidence,
            "outcome": outcome,
            "outcome_reason": outcome_reason,
            "builder_count": results.len(),
            "agent_count": results.len(),
            "successful_agents": successful_builders,
            "usable_agents": successful_builders,
            "degraded_agents": 0,
            "failed_agents": failed_builders,
            "total_turns": total_turns,
            "total_duration_ms": total_duration_ms,
            "paths_examined": unique_files,
            "paths_examined_count": unique_files.len(),
            "files_examined": unique_files,
            "builders": builders,
            "background_processes": background_processes,
            "lines_added": stats.lines_added,
            "lines_removed": stats.lines_removed,
            "files_modified": stats.files_modified,
            "lock_contentions": stats.lock_contentions,
            "total_lock_wait_ms": stats.total_lock_wait_ms,
            "high_contention_files": high_contention_files,
            "coverage_gap_notice": coverage_gap_notice,
            "errors": errors,
            "delegation_policy": delegation_policy.audit_json(),
        });

        if let Some(store) = delegated_store.as_ref() {
            let final_stage = match outcome {
                "success" => DelegatedRunStage::Complete,
                "partial" => DelegatedRunStage::Degraded,
                _ => DelegatedRunStage::Failed,
            };
            if let Err(err) = store.finalize_run(
                &delegated_run_id,
                final_stage,
                &payload,
                Some(&investigation_summary),
                failed_builders > 0,
            ) {
                warn!(delegated_run_id = %delegated_run_id, error = %err, "Failed to persist delegated build run final artifact");
            }
        }

        ToolResult::success_data(payload)
    }
}

#[cfg(all(test, unix))]
mod tests {
    use std::time::Duration;

    use crate::agent::subagent::DelegatedProcessArtifact;
    use crate::process::ProcessRegistry;

    use super::{
        active_process_handoff_summary, build_confidence_with_handoff,
        classify_build_outcome_with_handoff, revalidate_background_processes,
    };

    fn captured_process(process_id: &str, endpoint_hints: Vec<String>) -> DelegatedProcessArtifact {
        DelegatedProcessArtifact {
            process_id: process_id.to_string(),
            status: "running".to_string(),
            command: "captured startup command".to_string(),
            working_dir: "/tmp".to_string(),
            endpoint_hints,
            reused_existing: false,
        }
    }

    async fn wait_until_terminal(registry: &ProcessRegistry, owner_id: &str, process_id: &str) {
        tokio::time::timeout(Duration::from_secs(2), async {
            loop {
                if registry
                    .get_for_user(owner_id, process_id)
                    .await
                    .is_some_and(|process| !process.is_active())
                {
                    return;
                }
                tokio::time::sleep(Duration::from_millis(10)).await;
            }
        })
        .await
        .expect("tracked process should reach a terminal state");
    }

    #[tokio::test]
    async fn process_that_dies_before_aggregation_is_not_an_active_handoff() {
        let temp = tempfile::tempdir().expect("tempdir");
        let registry = ProcessRegistry::new();
        let owner_id = "owner-a";
        let process_id = registry
            .spawn_for_user(
                owner_id,
                "exit 0".to_string(),
                temp.path().to_path_buf(),
                None,
            )
            .await
            .expect("spawn short process");
        wait_until_terminal(&registry, owner_id, &process_id).await;

        // Model the earlier Bash startup artifact, which may still say
        // `running` even though the registry monitor has observed completion.
        let mut processes = vec![captured_process(
            &process_id,
            vec!["127.0.0.1:5940".to_string()],
        )];
        revalidate_background_processes(&mut processes, Some(&registry), Some(owner_id)).await;

        assert_eq!(processes[0].status, "done");
        assert!(active_process_handoff_summary(&processes).is_none());
        assert_eq!(
            classify_build_outcome_with_handoff(1, 0, 0, false),
            "failed"
        );
        assert_eq!(build_confidence_with_handoff(0, 0, false), "low");
    }

    #[tokio::test]
    async fn non_endpoint_process_only_handoff_is_not_usable_build_evidence() {
        let temp = tempfile::tempdir().expect("tempdir");
        let registry = ProcessRegistry::new();
        let owner_id = "owner-a";
        let process_id = registry
            .spawn_for_user(
                owner_id,
                "sleep 5".to_string(),
                temp.path().to_path_buf(),
                None,
            )
            .await
            .expect("spawn sleep process");
        let mut processes = vec![captured_process(&process_id, Vec::new())];

        revalidate_background_processes(&mut processes, Some(&registry), Some(owner_id)).await;
        let has_handoff = active_process_handoff_summary(&processes).is_some();

        assert!(!has_handoff);
        assert_eq!(
            classify_build_outcome_with_handoff(1, 0, 0, has_handoff),
            "failed"
        );
        assert_eq!(build_confidence_with_handoff(0, 0, has_handoff), "low");

        registry
            .kill_for_user(owner_id, &process_id)
            .await
            .expect("kill sleep process");
    }

    #[tokio::test]
    async fn active_handoff_is_owner_scoped_and_does_not_downgrade_file_evidence() {
        let temp = tempfile::tempdir().expect("tempdir");
        let registry = ProcessRegistry::new();
        let owner_id = "owner-a";
        let process_id = registry
            .spawn_for_user(
                owner_id,
                "sleep 5".to_string(),
                temp.path().to_path_buf(),
                None,
            )
            .await
            .expect("spawn tracked process");
        let mut owned = vec![captured_process(
            &process_id,
            vec!["127.0.0.1:5940".to_string()],
        )];

        revalidate_background_processes(&mut owned, Some(&registry), Some(owner_id)).await;
        assert_eq!(owned[0].status, "running");
        assert!(active_process_handoff_summary(&owned)
            .is_some_and(|summary| summary.contains("127.0.0.1:5940")));

        let mut other_owner = owned.clone();
        revalidate_background_processes(&mut other_owner, Some(&registry), Some("owner-b")).await;
        assert_eq!(other_owner[0].status, "missing");
        assert!(active_process_handoff_summary(&other_owner).is_none());

        // Existing file-modifying build evidence remains the basis for the
        // normal high-confidence classification; process readiness is not.
        assert_eq!(
            classify_build_outcome_with_handoff(1, 0, 2, true),
            "success"
        );
        assert_eq!(build_confidence_with_handoff(0, 2, true), "high");

        registry
            .kill_for_user(owner_id, &process_id)
            .await
            .expect("kill tracked process");
    }
}
