use std::sync::Arc;

use serde_json::json;
use tracing::{debug, info, warn};
use uuid::Uuid;

use crate::agent::context::build_subagent_project_context;
use crate::agent::subagent::{
    build_context::SharedBuildContext, AgentCapability, AgentProgress, BackpressureSignal,
    BuildIsolationMaterializationGuard, BuildIsolationSet, DelegatedProcessArtifact, SubAgentPool,
    SubAgentResult, SubAgentTask, SubAgentTermination,
};
use crate::agent::DelegationCoordinator;
use crate::agent::{AgentCancellation, DelegatedRunStage};
use crate::storage::{
    DelegatedRunCreateOutcome, DelegatedRunLease, DelegatedRunRole, DelegatedRunScope,
    DelegatedRunStartInput, DelegationCompletionPolicy, DelegationExecutionMode,
    DelegationExecutorKind, DelegationFailurePolicy, DelegationGovernance, DelegationGroupContract,
    DelegationGroupStartInput, DelegationTaskSpec, DelegationWriterMode, ProjectSettings,
};
use crate::tools::registry::DelegationPolicy;
use crate::tools::{ToolContext, ToolResult};

use super::single::build_detached_executor_envelope;
use super::{
    agent_progress_for_terminal_stage, background_started_result, build_confidence,
    build_coverage_gap_notice, build_investigation_summary, classify_build_outcome,
    delegated_persistence_error, delegated_workspace_scope, existing_continuation_error,
    notify_child_completion, open_delegated_run_store, persist_background_delegated_artifact,
    persist_delegated_artifact, AgentTool, Params,
};

fn deduplicate_background_processes(processes: &mut Vec<DelegatedProcessArtifact>) {
    processes.sort_by(|left, right| left.process_id.cmp(&right.process_id));
    processes.dedup_by(|left, right| left.process_id == right.process_id);
}

async fn revalidate_background_processes(
    processes: &mut [DelegatedProcessArtifact],
    registry: Option<&crate::process::ProcessRegistry>,
    process_owner_id: Option<&str>,
) {
    let Some(registry) = registry else {
        // A captured startup result is not sufficient proof at finalization if
        // the inherited registry is unavailable. Keep the artifact for audit,
        // but make sure it cannot be classified as an active handoff.
        for process in processes {
            process.status = "unverified".to_string();
        }
        return;
    };

    for process in processes {
        let current = match process_owner_id {
            Some(owner_id) => registry.get_for_user(owner_id, &process.process_id).await,
            // Single-tenant callers use the registry's default owner. Process
            // IDs are generated by the registry and originate in this result.
            None => registry.get(&process.process_id).await,
        };
        process.status = current
            .as_ref()
            .map(|info| info.display_status().to_string())
            .unwrap_or_else(|| "missing".to_string());
    }
}

async fn discard_unowned_build_isolation(
    isolation: &mut Option<BuildIsolationSet>,
    delegated_run_id: &str,
) {
    let Some(isolation) = isolation.take() else {
        return;
    };
    if let Err(error) = isolation.discard().await {
        warn!(
            delegated_run_id,
            %error,
            "Failed to discard an unowned delegated build isolation batch"
        );
    }
}

fn active_process_handoff_summary(processes: &[DelegatedProcessArtifact]) -> Option<String> {
    let active = processes
        .iter()
        .filter(|process| {
            matches!(process.status.as_str(), "running" | "suspended")
                && !process.endpoint_hints.is_empty()
        })
        .collect::<Vec<_>>();
    if active.is_empty() {
        return None;
    }

    Some(
        active
            .iter()
            .map(|process| {
                let endpoints = if process.endpoint_hints.is_empty() {
                    String::new()
                } else {
                    format!(" at {}", process.endpoint_hints.join(", "))
                };
                format!("{} ({}){}", process.process_id, process.status, endpoints)
            })
            .collect::<Vec<_>>()
            .join("; "),
    )
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct BuildResultCounts {
    complete: usize,
    degraded: usize,
    cancelled: usize,
    usable: usize,
    failed: usize,
}

fn is_complete_build_result(result: &SubAgentResult) -> bool {
    result.termination == SubAgentTermination::Completed && result.has_usable_evidence()
}

fn is_degraded_build_result(result: &SubAgentResult) -> bool {
    result.termination.is_degraded_interruption() && result.has_usable_evidence()
}

fn is_cancelled_build_result(result: &SubAgentResult) -> bool {
    result.termination == SubAgentTermination::Cancelled
}

fn build_result_counts(results: &[SubAgentResult]) -> BuildResultCounts {
    let complete = results
        .iter()
        .filter(|result| is_complete_build_result(result))
        .count();
    let degraded = results
        .iter()
        .filter(|result| is_degraded_build_result(result))
        .count();
    let cancelled = results
        .iter()
        .filter(|result| is_cancelled_build_result(result))
        .count();
    let usable = complete.saturating_add(degraded);

    BuildResultCounts {
        complete,
        degraded,
        cancelled,
        usable,
        failed: results
            .len()
            .saturating_sub(usable.saturating_add(cancelled)),
    }
}

fn classify_build_outcome_with_handoff(
    results_len: usize,
    incomplete_builders: usize,
    modified_files: usize,
    has_active_process_handoff: bool,
) -> &'static str {
    if modified_files > 0 {
        return classify_build_outcome(results_len, incomplete_builders, modified_files);
    }
    if results_len > 0 && has_active_process_handoff {
        return if incomplete_builders == 0 {
            "success"
        } else {
            "partial"
        };
    }
    classify_build_outcome(results_len, incomplete_builders, modified_files)
}

fn build_confidence_with_handoff(
    failed_builders: usize,
    modified_files: usize,
    has_active_process_handoff: bool,
) -> &'static str {
    if modified_files > 0 {
        return build_confidence(failed_builders, modified_files);
    }
    if failed_builders == 0 && has_active_process_handoff {
        // Registry liveness proves that the process is controllable, but an
        // endpoint hint parsed from its command is not a readiness probe.
        return "medium";
    }
    build_confidence(failed_builders, modified_files)
}

fn build_summary_with_handoff(
    successful_builders: usize,
    degraded_builders: usize,
    cancelled_builders: usize,
    failed_builders: usize,
    modified_files: usize,
    lines_added: usize,
    lines_removed: usize,
    process_handoff: Option<&str>,
) -> String {
    let build_summary = build_investigation_summary(
        successful_builders,
        degraded_builders,
        cancelled_builders,
        failed_builders,
        modified_files,
        lines_added,
        lines_removed,
    );

    match (modified_files > 0, process_handoff) {
        (true, Some(handoff)) => format!(
            "{build_summary} Delegated build also handed off tracked process(es): {handoff}. Process liveness was revalidated at aggregation; endpoint readiness remains unverified."
        ),
        (false, Some(handoff)) => format!(
            "Delegated build handed off tracked process(es): {handoff}. Process liveness was revalidated at aggregation; endpoint readiness remains unverified."
        ),
        (_, None) => build_summary,
    }
}

impl AgentTool {
    // Build
    // -----------------------------------------------------------------------

    pub(super) async fn execute_build(&self, params: Params, ctx: &ToolContext) -> ToolResult {
        if ctx.project_dir.is_none() {
            return ToolResult::error(
                "No project directory is selected for this session. Create or choose a project directory, then promote the session before using build.",
            );
        }

        let client = self.resolve_client(ctx);
        let workspace_scope = match delegated_workspace_scope(
            ctx.project_dir
                .as_deref()
                .expect("build checked project directory"),
        ) {
            Ok(scope) => scope,
            Err(error) => {
                return ToolResult::error_with_code("invalid_project_workspace", error);
            }
        };

        // Create shared build context
        let context = Arc::new(SharedBuildContext::new());

        // Merge conventions: project settings as base, user params override/extend
        let project_settings = ctx
            .project_dir
            .as_ref()
            .map(|p| ProjectSettings::load(p))
            .unwrap_or_default();
        let mut conventions = project_settings.conventions.unwrap_or_default();
        if let Some(user_conventions) = &params.conventions {
            conventions.extend(user_conventions.iter().cloned());
        }
        if !conventions.is_empty() {
            context.set_conventions(conventions);
        }

        // Adaptive scheduling starts every component eagerly. An explicit value
        // is a user ceiling, not a hidden product cap.
        let num_components = params.components.as_ref().map(|c| c.len()).unwrap_or(1);
        let concurrency = params.max_concurrency;

        // Build tasks - all use Opus for high-quality code generation
        let mut tasks: Vec<SubAgentTask> = Vec::new();
        let delegated_run_id = Uuid::new_v4().to_string();
        let capabilities = params
            .capabilities
            .iter()
            .map(|capability| AgentCapability::parse(capability))
            .collect::<Result<std::collections::BTreeSet<_>, _>>()
            .expect("AgentSpec validated parallel child capabilities");
        let delegation_policy = DelegationPolicy::for_subagent_child(
            ctx.permission_mode,
            params.max_turns,
            capabilities.contains(&AgentCapability::Read),
            capabilities.contains(&AgentCapability::Write),
            capabilities.contains(&AgentCapability::Execute),
        )
        .with_supervised_approval(ctx.supervised_approval_granted)
        .with_execution_tool_allowlist(ctx.execution_tool_allowlist.as_ref());
        let mut delegated_lease = open_delegated_run_store(ctx).map(DelegatedRunLease::new);
        let background = params.run_in_background.unwrap_or(false);
        if background && ctx.db_path.is_none() {
            return ToolResult::error_with_code(
                "agent_persistence_error",
                "Background build was not started because this session has no durable database.",
            );
        }
        if background && delegated_lease.is_none() {
            return ToolResult::error_with_code(
                "agent_persistence_error",
                "Background build was not started because its delegated-run database could not be opened.",
            );
        }
        if background && ctx.session_id.is_none() {
            return ToolResult::error_with_code(
                "agent_persistence_error",
                "Background build was not started because it has no durable parent session.",
            );
        }
        let mut target_scope = vec![workspace_scope.clone()];
        let parent_name = params.name.as_deref().unwrap_or("child");
        let project_context =
            build_subagent_project_context(&ctx.working_dir, ctx.project_dir.as_deref());

        if let Some(ref components) = params.components {
            let total = components.len();
            let other_components: Vec<_> = components.iter().map(|c| c.as_str()).collect();

            // One agent per component - each gets their own file for TRUE parallelism
            for (i, component) in components.iter().enumerate() {
                let component_name = component.split_whitespace().next().unwrap_or("component");
                let name = format!("{parent_name} / {component_name}");
                let others: Vec<_> = other_components
                    .iter()
                    .enumerate()
                    .filter(|(j, _)| *j != i)
                    .map(|(j, c)| format!("  - Builder {}: {}", j, c))
                    .collect();

                // Create detailed prompt emphasizing SEPARATE FILES
                let task_prompt = format!(
                    "You are Builder {} of {} in a parallel build team.\n\n\
                     YOUR COMPONENT: {}\n\n\
                     OVERALL GOAL:\n{}\n\n\
                     OTHER BUILDERS (working in parallel):\n{}\n\n\
                     PARALLEL BUILD STRATEGY:\n\
                     1. Create YOUR OWN file(s) for your component - don't wait for others\n\
                     2. Name files clearly: {}_something.ext (e.g., game_engine.py, snake_logic.py)\n\
                     3. If you need to import from another builder's module, assume it exists\n\
                     4. Export clear interfaces (functions, classes) others can import\n\
                     5. At the end, if a main.py/main.rs is needed, Builder 0 creates it and imports all modules\n\n\
                     COORDINATION:\n\
                     - Check [SHARED TYPES] for interfaces other builders registered\n\
                     - Register YOUR public functions/classes so others can import them\n\
                     - File locks are automatic - but you shouldn't need them if using separate files\n\n\
                     PROJECT CONTEXT:\n{}\n\n\
                     BUILD YOUR COMPONENT NOW. Create your file(s) and implement fully.",
                    i, total,
                    component,
                    params.prompt,
                    if others.is_empty() { "  (none - you're solo)".to_string() } else { others.join("\n") },
                    component_name.to_lowercase().replace(' ', "_"),
                    project_context,
                );

                let mut task = SubAgentTask::new(format!("builder-{}", i), task_prompt)
                    .with_name(name.clone())
                    .with_working_dir(ctx.working_dir.clone())
                    .with_delegated_run_id(delegated_run_id.clone())
                    .with_delegation_policy(delegation_policy.clone())
                    .with_process_context(
                        ctx.process_registry.clone(),
                        ctx.user_id.clone(),
                        ctx.session_id.clone(),
                    )
                    .with_provider_call_trace(ctx.provider_call_trace.clone());
                if let Some(sandbox_root) = ctx.sandbox_root.clone() {
                    task = task.with_sandbox_root(sandbox_root);
                }
                if let Some(max_turns) = params.max_turns {
                    task = task.with_max_turns(max_turns);
                }

                // Attach plan task ID if provided for auto-completion
                if let Some(ref task_ids) = params.task_ids {
                    if let Some(plan_task_id) = task_ids.get(i) {
                        task = task.with_plan_task_id(plan_task_id);
                    }
                }

                target_scope.push(DelegatedRunScope {
                    label: name,
                    path: component.clone(),
                    kind: "component".to_string(),
                });
                tasks.push(task);
            }
        } else {
            // Single builder for the whole task
            target_scope.push(DelegatedRunScope {
                label: "main".to_string(),
                path: ".".to_string(),
                kind: "project".to_string(),
            });
            let mut task = SubAgentTask::new("builder-main", params.prompt.clone())
                .with_name("main")
                .with_working_dir(ctx.working_dir.clone())
                .with_delegated_run_id(delegated_run_id.clone())
                .with_delegation_policy(delegation_policy.clone())
                .with_process_context(
                    ctx.process_registry.clone(),
                    ctx.user_id.clone(),
                    ctx.session_id.clone(),
                )
                .with_provider_call_trace(ctx.provider_call_trace.clone());
            if let Some(sandbox_root) = ctx.sandbox_root.clone() {
                task = task.with_sandbox_root(sandbox_root);
            }
            if let Some(max_turns) = params.max_turns {
                task = task.with_max_turns(max_turns);
            }
            tasks.push(task);
        }

        // Serialize the narrow pre-group materialization interval. If a prior
        // process died after preparing these deterministic worktrees but
        // before creating the durable group, remove only the abandoned batch
        // after proving that no canonical group owns it.
        let materialization_guard = if tasks.len() > 1 {
            let guard =
                match BuildIsolationMaterializationGuard::acquire(delegated_run_id.clone()).await {
                    Ok(guard) => guard,
                    Err(error) => {
                        return ToolResult::error_with_code(
                            "agent_workspace_isolation_error",
                            format!(
                                "Parallel builders could not reserve their isolated batch: {error}"
                            ),
                        );
                    }
                };
            if let Some(db_path) = ctx.db_path.as_ref() {
                let coordinator = DelegationCoordinator::new(db_path.clone());
                match coordinator.get_group(&delegated_run_id) {
                    Ok(Some(_)) => {
                        return ToolResult::error_with_code(
                            "agent_persistence_error",
                            "Delegated build was not started because its durable group already exists.",
                        );
                    }
                    Ok(None) => {
                        if let Err(error) = guard
                            .remove_abandoned_preparation(
                                ctx.project_dir
                                    .as_ref()
                                    .expect("build checked project directory")
                                    .clone(),
                                tasks.len(),
                            )
                            .await
                        {
                            return ToolResult::error_with_code(
                                "agent_workspace_isolation_error",
                                format!(
                                    "Parallel builders found an ambiguous abandoned isolation batch and retained it for recovery: {error}"
                                ),
                            );
                        }
                    }
                    Err(error) => {
                        return ToolResult::error_with_code(
                            "agent_persistence_error",
                            format!("Parallel builders could not check durable batch ownership: {error}"),
                        );
                    }
                }
            }
            Some(guard)
        } else {
            None
        };

        // Real parallel writers execute in detached Git worktrees captured
        // from the same dirty source snapshot. Non-Git projects deliberately
        // retain the serial shared-workspace compatibility path.
        let mut build_isolation = if tasks.len() > 1 {
            match BuildIsolationSet::prepare(
                ctx.project_dir
                    .as_ref()
                    .expect("build checked project directory")
                    .clone(),
                ctx.working_dir.clone(),
                delegated_run_id.clone(),
                tasks.iter().map(|task| task.id.clone()).collect(),
            )
            .await
            {
                Ok(isolation) => isolation,
                Err(error) => {
                    return ToolResult::error_with_code(
                        "agent_workspace_isolation_error",
                        format!(
                            "Parallel builders were not started because isolated workspaces could not be prepared: {error}"
                        ),
                    );
                }
            }
        } else {
            None
        };
        if let Some(isolation) = build_isolation.as_ref() {
            for task in &mut tasks {
                let workspace = isolation
                    .workspaces()
                    .iter()
                    .find(|workspace| workspace.task_id == task.id)
                    .expect("isolation workspace exists for every builder");
                let source_project = ctx
                    .project_dir
                    .as_ref()
                    .expect("build checked project directory")
                    .display()
                    .to_string();
                let source_working = ctx.working_dir.display().to_string();
                task.prompt = task
                    .prompt
                    .replace(&source_project, &workspace.root.display().to_string())
                    .replace(
                        &source_working,
                        &workspace.working_dir.display().to_string(),
                    );
                task.prompt.push_str(&format!(
                    "\n\n[ISOLATED WRITE WORKSPACE]\nAll writes and commands for this attempt must remain under {}. The authoritative source workspace is unchanged until parent synthesis applies your patch.\n[/ISOLATED WRITE WORKSPACE]",
                    workspace.root.display()
                ));
                task.working_dir = workspace.working_dir.clone();
                task.sandbox_root = Some(workspace.root.clone());
            }
        }

        let durable_run_started = if let (Some(lease), Some(session_id)) =
            (delegated_lease.as_mut(), ctx.session_id.as_ref())
        {
            let start = DelegatedRunStartInput {
                delegated_run_id: delegated_run_id.clone(),
                parent_session_id: session_id.clone(),
                parent_tool_call_id: ctx.tool_use_id.clone(),
                role: DelegatedRunRole::Build,
                stage: DelegatedRunStage::Created,
                provider: Some(client.provider_id().to_string()),
                model: Some(client.config().model.clone()),
                resumable: true,
                resumed_from_run_id: params.resumed_from_run_id.clone(),
                target_scope: target_scope.clone(),
            };
            let create = if background {
                lease.create_background_run_with_child_contract(
                    &start,
                    Some(parent_name),
                    &capabilities,
                )
            } else {
                lease.create_run_with_child_contract(&start, Some(parent_name), &capabilities)
            };
            match create {
                Ok(DelegatedRunCreateOutcome::Created) => {}
                Ok(DelegatedRunCreateOutcome::ExistingContinuation {
                    delegated_run_id,
                    resumed_from_run_id,
                }) => {
                    discard_unowned_build_isolation(&mut build_isolation, &delegated_run_id).await;
                    return existing_continuation_error(&resumed_from_run_id, &delegated_run_id);
                }
                Err(error) => {
                    discard_unowned_build_isolation(&mut build_isolation, &delegated_run_id).await;
                    return ToolResult::error_with_code(
                        "agent_persistence_error",
                        format!(
                            "Delegated build was not started because its durable run record could not be created: {error}"
                        ),
                    );
                }
            }
            true
        } else {
            false
        };
        if background && !durable_run_started {
            discard_unowned_build_isolation(&mut build_isolation, &delegated_run_id).await;
            return ToolResult::error_with_code(
                "agent_persistence_error",
                "Background build was not started because durable run creation was unavailable.",
            );
        }

        // Establish the parent-owned group only after its compatibility run
        // exists. Older clients continue to consume that aggregate run while
        // every component now executes under a distinct durable logical task.
        let mut delegation_coordinator = None;
        if durable_run_started && !tasks.is_empty() {
            let db_path = ctx
                .db_path
                .as_ref()
                .expect("durable delegated build has a database path");
            let session_id = ctx
                .session_id
                .as_ref()
                .expect("durable delegated build has a parent session");
            let coordinator = DelegationCoordinator::new(db_path.clone());
            let resolved_model = client.resolved_model().wire_model_id.clone();
            let task_specs = match tasks
                .iter()
                .enumerate()
                .map(|(index, task)| {
                    let isolated = build_isolation.as_ref().and_then(|isolation| {
                        isolation
                            .workspaces()
                            .iter()
                            .find(|workspace| workspace.task_id == task.id)
                    });
                    let delegation_task_id = format!("{delegated_run_id}:task:{index}");
                    let executor_envelope = if background {
                        Some(build_detached_executor_envelope(
                            ctx,
                            &delegation_task_id,
                            &task.name,
                            &task.prompt,
                            DelegationExecutorKind::Build,
                            DelegatedRunRole::Build,
                            &client.resolved_model().key,
                            &resolved_model,
                            &task.working_dir,
                            task.sandbox_root.as_deref().unwrap_or(&task.working_dir),
                        )?)
                    } else {
                        None
                    };
                    Ok::<_, String>(DelegationTaskSpec {
                        delegation_task_id,
                        task_key: task.id.clone(),
                        objective: task.prompt.clone(),
                        role: DelegatedRunRole::Build,
                        target_scope: vec![
                            workspace_scope.clone(),
                            DelegatedRunScope {
                                label: task.name.clone(),
                                path: task.id.clone(),
                                kind: "component".to_string(),
                            },
                        ],
                        max_attempts: 2,
                        writer_mode: if isolated.is_some() {
                            DelegationWriterMode::Isolated
                        } else {
                            DelegationWriterMode::Shared
                        },
                        attempt_workspace: isolated
                            .map(|workspace| workspace.root.display().to_string()),
                        workspace_baseline: isolated
                            .map(|workspace| workspace.baseline_commit.clone()),
                        executor_envelope,
                    })
                })
                .collect::<Result<Vec<_>, _>>()
            {
                Ok(specifications) => specifications,
                Err(error) => {
                    discard_unowned_build_isolation(&mut build_isolation, &delegated_run_id).await;
                    return ToolResult::error_with_code("agent_persistence_error", error);
                }
            };
            let group_input = DelegationGroupStartInput {
                delegation_group_id: delegated_run_id.clone(),
                parent_session_id: session_id.clone(),
                parent_tool_call_id: ctx.tool_use_id.clone(),
                contract: DelegationGroupContract {
                    execution_mode: if background {
                        DelegationExecutionMode::Detached
                    } else {
                        DelegationExecutionMode::Foreground
                    },
                    completion_policy: DelegationCompletionPolicy::AllSettled,
                    failure_policy: DelegationFailurePolicy::Continue,
                    governance: DelegationGovernance {
                        permission_mode: ctx.permission_mode,
                        delegated_turn_budget: params.max_turns.unwrap_or(20),
                        max_parallelism: concurrency.unwrap_or(tasks.len()).max(1).min(tasks.len()),
                        execution_tool_allowlist: delegation_policy
                            .execution_tool_allowlist
                            .clone(),
                        delegation_policy: delegation_policy.clone(),
                    },
                },
                tasks: task_specs.clone(),
            };
            if let Err(error) = coordinator.create_group(&group_input) {
                if matches!(coordinator.get_group(&delegated_run_id), Ok(None)) {
                    discard_unowned_build_isolation(&mut build_isolation, &delegated_run_id).await;
                }
                return ToolResult::error_with_code(
                    "agent_persistence_error",
                    format!(
                        "Delegated build was not started because its durable group could not be created: {error}"
                    ),
                );
            }
            for (task, specification) in tasks.iter_mut().zip(task_specs) {
                *task = task.clone().with_delegation_task(
                    delegated_run_id.clone(),
                    specification.delegation_task_id,
                );
                task.max_turns_override = Some(params.max_turns.unwrap_or(20));
            }
            delegation_coordinator = Some(coordinator);
        }
        drop(materialization_guard);

        info!("Agent tool (build): Created {} builder tasks", tasks.len());
        for (i, task) in tasks.iter().enumerate() {
            debug!("Builder {}: id={}, name={}", i, task.id, task.name);
        }

        // Create one cancellation root and one broadcast mailbox per background run.
        let (pool_cancellation, background_runtime_registration, background_host_cancellation) =
            if background {
                let run_cancellation = self.cancellation.child_token();
                let (first_mailbox, runtime_registration) = self.runtime.register_guarded(
                    delegated_run_id.clone(),
                    params.name.as_deref().unwrap_or("build"),
                    ctx.session_id.clone(),
                    run_cancellation.clone(),
                );
                for (index, task) in tasks.iter_mut().enumerate() {
                    let mailbox = if index == 0 {
                        first_mailbox.clone()
                    } else {
                        self.runtime
                            .subscribe(&delegated_run_id)
                            .expect("registered build runtime")
                    };
                    *task = task.clone().with_mailbox(mailbox);
                }
                (
                    AgentCancellation::from_token(run_cancellation.clone()),
                    Some(runtime_registration),
                    Some(run_cancellation),
                )
            } else {
                let cancellation = ctx
                    .execution_cancellation
                    .clone()
                    .map(AgentCancellation::from_token)
                    .unwrap_or_else(|| self.cancellation.clone());
                (cancellation, None, None)
            };

        // Create pool and execute with build context
        let mut pool = SubAgentPool::new(client, pool_cancellation)
            .with_override_model(ctx.current_model.clone());
        if let Some(ceiling) = concurrency {
            pool = pool.with_concurrency(ceiling);
        }
        if let Some(coordinator) = delegation_coordinator.clone() {
            pool = pool.with_delegation_coordinator(coordinator);
        }

        info!(
            "Agent tool (build): Starting adaptive builder pool with concurrency_ceiling={:?} (components={}), background={}",
            concurrency, num_components, params.run_in_background.unwrap_or(false)
        );

        // ── Background mode ──────────────────────────────────────────
        if background {
            let bg_delegated_run_id = delegated_run_id.clone();
            let bg_db_path = ctx.db_path.clone();
            let bg_session_id = ctx.session_id.clone();
            let bg_user_id = ctx.user_id.clone();
            let bg_workspace_root = ctx.filesystem_access_root();
            let bg_child_name = params.name.clone().unwrap_or_else(|| "child".to_string());
            let bg_delegation_policy = delegation_policy.clone();
            let bg_process_registry = ctx.process_registry.clone();
            let bg_process_owner_id = ctx.user_id.clone();
            let bg_group_coordinator = delegation_coordinator.clone();
            let mut bg_build_isolation = build_isolation.take();
            let bg_integration_workspace = workspace_scope.path.clone();
            let mut bg_runtime_registration = background_runtime_registration
                .expect("background build registered live runtime ownership");
            let progress_tx = ctx.agent_progress_tx.clone();
            let bg_runtime = self.runtime.clone();
            let mut bg_run_lease = delegated_lease
                .take()
                .expect("background build start has an armed durable lease");
            let bg_host_heartbeat = match bg_run_lease.start_background_host_heartbeat(
                &bg_delegated_run_id,
                background_host_cancellation
                    .expect("background build has an execution cancellation token"),
            ) {
                Ok(heartbeat) => heartbeat,
                Err(error) => {
                    discard_unowned_build_isolation(&mut bg_build_isolation, &bg_delegated_run_id)
                        .await;
                    return ToolResult::error_with_code(
                        "agent_persistence_error",
                        format!(
                            "Background build was not started because its durable host lease could not start: {error}"
                        ),
                    );
                }
            };

            tokio::spawn(async move {
                let _bg_host_heartbeat = bg_host_heartbeat;
                // Keep a clone for the completion event after execute_builders consumes the tx
                let completion_tx = progress_tx.clone();

                let mut results = if let Some(progress_tx) = progress_tx {
                    pool.execute_builders(tasks, context.clone(), progress_tx)
                        .await
                } else {
                    let (tx, _rx) = tokio::sync::mpsc::unbounded_channel();
                    pool.execute_builders(tasks, context.clone(), tx).await
                };
                let synthesis_permit = if let Some(coordinator) = bg_group_coordinator.as_ref() {
                    match coordinator.begin_synthesis(&bg_delegated_run_id) {
                        Ok(permit) => Some(permit),
                        Err(error) => {
                            tracing::error!(
                                delegated_run_id = %bg_delegated_run_id,
                                %error,
                                "Stopping background aggregate because durable synthesis ownership was not acquired"
                            );
                            return;
                        }
                    }
                } else {
                    None
                };
                if synthesis_permit
                    .as_ref()
                    .is_some_and(|permit| permit.cancellation().is_cancelled())
                {
                    tracing::warn!(
                        delegated_run_id = %bg_delegated_run_id,
                        "Stopping background integration after durable synthesis ownership was lost"
                    );
                    return;
                }
                if let Some(isolation) = bg_build_isolation {
                    if let Some(integration_permit) = pool
                        .acquire_integration_writer(
                            bg_session_id
                                .clone()
                                .unwrap_or_else(|| bg_delegated_run_id.clone()),
                            bg_integration_workspace,
                        )
                        .await
                    {
                        if synthesis_permit
                            .as_ref()
                            .is_some_and(|permit| permit.cancellation().is_cancelled())
                        {
                            integration_permit.complete(BackpressureSignal::Cancelled);
                            tracing::warn!(
                                delegated_run_id = %bg_delegated_run_id,
                                "Stopping background integration after synthesis lease loss"
                            );
                            return;
                        }
                        results = isolation.integrate(results).await;
                        let signal = if results.iter().any(|result| !result.success) {
                            BackpressureSignal::Failed
                        } else {
                            BackpressureSignal::Healthy
                        };
                        integration_permit.complete(signal);
                    } else {
                        for result in &mut results {
                            result.success = false;
                            result.termination = SubAgentTermination::Cancelled;
                            result.error = Some(
                                "Isolated build integration was cancelled; recovery workspaces were retained."
                                    .to_string(),
                            );
                        }
                    }
                }
                if synthesis_permit
                    .as_ref()
                    .is_some_and(|permit| permit.cancellation().is_cancelled())
                {
                    tracing::warn!(
                        delegated_run_id = %bg_delegated_run_id,
                        "Suppressing background aggregate publication after synthesis lease loss"
                    );
                    return;
                }

                for result in &mut results {
                    revalidate_background_processes(
                        &mut result.background_processes,
                        bg_process_registry.as_deref(),
                        bg_process_owner_id.as_deref(),
                    )
                    .await;
                }

                // Build the finalization payload (same logic as synchronous path)
                let stats = context.stats();
                let mut all_files: Vec<String> = Vec::new();
                let mut total_turns = 0;
                let mut total_duration_ms = 0u64;
                let mut errors: Vec<String> = Vec::new();
                let mut degradations: Vec<String> = Vec::new();
                let mut cancellations: Vec<String> = Vec::new();
                let mut builders = Vec::new();
                let mut background_processes = Vec::new();

                for result in &results {
                    builders.push(result.evidence_json());
                    background_processes.extend(result.background_processes.iter().cloned());
                    if is_cancelled_build_result(result) {
                        cancellations.push(format!("{}: cancelled", result.task_id));
                    } else if is_degraded_build_result(result) {
                        degradations.push(format!(
                            "{}: {}",
                            result.task_id,
                            result.outcome_reason()
                        ));
                    } else if !is_complete_build_result(result) {
                        errors.push(format!(
                            "{}: {}",
                            result.task_id,
                            result.error.as_deref().unwrap_or(result.outcome_reason())
                        ));
                    }
                    all_files.extend(result.files_examined.clone());
                    total_turns += result.turns_used;
                    total_duration_ms += result.duration_ms;
                }
                deduplicate_background_processes(&mut background_processes);

                let mut unique_files = Vec::new();
                for file in all_files {
                    if !unique_files.iter().any(|existing| existing == &file) {
                        unique_files.push(file);
                    }
                }

                let counts = build_result_counts(&results);
                let incomplete_builders = counts
                    .degraded
                    .saturating_add(counts.cancelled)
                    .saturating_add(counts.failed);
                let process_handoff = active_process_handoff_summary(&background_processes);
                let outcome = if counts.cancelled > 0 {
                    "cancelled"
                } else {
                    classify_build_outcome_with_handoff(
                        results.len(),
                        incomplete_builders,
                        stats.files_modified,
                        process_handoff.is_some(),
                    )
                };
                let confidence = build_confidence_with_handoff(
                    incomplete_builders,
                    stats.files_modified,
                    process_handoff.is_some(),
                );
                let outcome_reason = if counts.cancelled > 0 {
                    "cancelled"
                } else if stats.files_modified > 0 {
                    if incomplete_builders == 0 {
                        "file_modifications"
                    } else {
                        "mixed"
                    }
                } else if process_handoff.is_some() && incomplete_builders == 0 {
                    "active_process_handoff_readiness_unverified"
                } else if process_handoff.is_some() {
                    "partial_process_handoff"
                } else {
                    "no_usable_evidence"
                };
                let investigation_summary = build_summary_with_handoff(
                    counts.complete,
                    counts.degraded,
                    counts.cancelled,
                    counts.failed,
                    stats.files_modified,
                    stats.lines_added,
                    stats.lines_removed,
                    process_handoff.as_deref(),
                );
                let coverage_issues = errors
                    .iter()
                    .chain(degradations.iter())
                    .chain(cancellations.iter())
                    .cloned()
                    .collect::<Vec<_>>();
                let coverage_gap_notice = build_coverage_gap_notice(&coverage_issues);

                let payload = json!({
                    "delegated_run_id": bg_delegated_run_id,
                    "message": format!(
                        "Build completed: {} builders, {} turns, +{} -{} lines across {} files",
                        results.len(), total_turns, stats.lines_added, stats.lines_removed, stats.files_modified,
                    ),
                    "investigation_summary": investigation_summary,
                    "outcome": outcome,
                    "outcome_reason": outcome_reason,
                    "confidence": confidence,
                    "builder_count": results.len(),
                    "agent_count": results.len(),
                    "successful_agents": counts.complete,
                    "usable_agents": counts.usable,
                    "degraded_agents": counts.degraded,
                    "cancelled_agents": counts.cancelled,
                    "failed_agents": counts.failed,
                    "total_turns": total_turns,
                    "total_duration_ms": total_duration_ms,
                    "files_examined": unique_files,
                    "builders": builders,
                    "background_processes": background_processes,
                    "lines_added": stats.lines_added,
                    "lines_removed": stats.lines_removed,
                    "files_modified": stats.files_modified,
                    "coverage_gap_notice": coverage_gap_notice,
                    "degradations": degradations,
                    "cancellations": cancellations,
                    "errors": errors,
                    "delegation_policy": bg_delegation_policy.audit_json(),
                });

                let final_stage = match outcome {
                    "success" => DelegatedRunStage::Complete,
                    "partial" => DelegatedRunStage::Degraded,
                    "cancelled" => DelegatedRunStage::Cancelled,
                    _ => DelegatedRunStage::Failed,
                };
                let finalization = persist_background_delegated_artifact(
                    &bg_run_lease,
                    &bg_delegated_run_id,
                    final_stage,
                    &payload,
                    &investigation_summary,
                    true,
                );

                match finalization {
                    Ok(authoritative) => {
                        if let Some(synthesis_permit) = synthesis_permit {
                            let group_state = group_terminal_state(authoritative.stage);
                            if let Err(error) = synthesis_permit.finalize(group_state) {
                                tracing::error!(
                                    delegated_run_id = %bg_delegated_run_id,
                                    %error,
                                    "Suppressing background parent wake because delegation group finalization failed"
                                );
                                return;
                            }
                        }
                        bg_run_lease.disarm(&bg_delegated_run_id);
                        let build_success = authoritative.stage == DelegatedRunStage::Complete;
                        let authoritative_summary = authoritative
                            .human_review
                            .as_deref()
                            .unwrap_or(&investigation_summary);
                        if let Some(ref tx) = completion_tx {
                            let (status, current_action) =
                                agent_progress_for_terminal_stage(authoritative.stage);
                            if tx
                                .send(AgentProgress {
                                    delegated_run_id: Some(bg_delegated_run_id.clone()),
                                    task_id: bg_child_name.clone(),
                                    name: bg_child_name.clone(),
                                    identity: None,
                                    status,
                                    tool_count: 0,
                                    tokens: 0,
                                    current_action,
                                    completion_summary: Some(authoritative_summary.to_string()),
                                    lines_added: stats.lines_added,
                                    lines_removed: stats.lines_removed,
                                    completed_plan_task: None,
                                })
                                .is_err()
                            {
                                debug!("Background build progress channel disconnected (parent returned)");
                            }
                        }
                        if authoritative.stage != DelegatedRunStage::Cancelled {
                            if let Err(error) = notify_child_completion(
                                &bg_runtime,
                                bg_db_path.as_deref(),
                                bg_session_id.as_deref(),
                                bg_user_id.as_deref(),
                                bg_workspace_root.as_deref(),
                                &bg_delegated_run_id,
                                &bg_child_name,
                                build_success,
                                authoritative_summary,
                            ) {
                                warn!(
                                    delegated_run_id = %bg_delegated_run_id,
                                    %error,
                                    "Failed to queue background child completion"
                                );
                                let _ = bg_runtime
                                    .request_completion_reconciliation(bg_delegated_run_id.clone());
                            }
                        }
                        bg_runtime_registration.finish(build_success);
                    }
                    Err(error) => {
                        tracing::error!(
                            delegated_run_id = %bg_delegated_run_id,
                            %error,
                            "Suppressing background build completion because terminal finalization was not authoritative"
                        );
                        // Guard Drop schedules abnormal durable reconciliation.
                    }
                }
            });

            return background_started_result(
                &delegated_run_id,
                params.name.as_deref().unwrap_or("child"),
                params.name.as_deref(),
            );
        }

        // ── Synchronous mode (existing behavior) ─────────────────────

        // Execute builders with progress channel if available
        let mut results = if let Some(ref progress_tx) = ctx.agent_progress_tx {
            pool.execute_builders(tasks, context.clone(), progress_tx.clone())
                .await
        } else {
            // Fallback: create a dummy channel and discard progress
            let (tx, _rx) = tokio::sync::mpsc::unbounded_channel();
            pool.execute_builders(tasks, context.clone(), tx).await
        };
        let synthesis_permit = if let Some(coordinator) = delegation_coordinator.as_ref() {
            match coordinator.begin_synthesis(&delegated_run_id) {
                Ok(permit) => Some(permit),
                Err(error) => {
                    return ToolResult::error_with_code(
                        "agent_delegation_synthesis_busy",
                        format!("Delegation synthesis could not be claimed: {error}"),
                    );
                }
            }
        } else {
            None
        };
        if synthesis_permit
            .as_ref()
            .is_some_and(|permit| permit.cancellation().is_cancelled())
        {
            return ToolResult::error_with_code(
                "agent_delegation_synthesis_lost",
                "Delegation synthesis ownership was lost before build integration; recovery workspaces were retained.",
            );
        }
        if let Some(isolation) = build_isolation {
            if let Some(integration_permit) = pool
                .acquire_integration_writer(
                    ctx.session_id
                        .clone()
                        .unwrap_or_else(|| delegated_run_id.clone()),
                    workspace_scope.path.clone(),
                )
                .await
            {
                if synthesis_permit
                    .as_ref()
                    .is_some_and(|permit| permit.cancellation().is_cancelled())
                {
                    integration_permit.complete(BackpressureSignal::Cancelled);
                    return ToolResult::error_with_code(
                        "agent_delegation_synthesis_lost",
                        "Delegation synthesis ownership was lost while waiting to integrate; recovery workspaces were retained.",
                    );
                }
                results = isolation.integrate(results).await;
                let signal = if results.iter().any(|result| !result.success) {
                    BackpressureSignal::Failed
                } else {
                    BackpressureSignal::Healthy
                };
                integration_permit.complete(signal);
            } else {
                for result in &mut results {
                    result.success = false;
                    result.termination = SubAgentTermination::Cancelled;
                    result.error = Some(
                        "Isolated build integration was cancelled; recovery workspaces were retained."
                            .to_string(),
                    );
                }
            }
        }
        if synthesis_permit
            .as_ref()
            .is_some_and(|permit| permit.cancellation().is_cancelled())
        {
            return ToolResult::error_with_code(
                "agent_delegation_synthesis_lost",
                "Delegation synthesis ownership was lost before aggregate publication; inspect the retained integration marker/workspaces.",
            );
        }

        for result in &mut results {
            revalidate_background_processes(
                &mut result.background_processes,
                ctx.process_registry.as_deref(),
                ctx.user_id.as_deref(),
            )
            .await;
        }

        info!(
            "Agent tool (build): Builder pool returned {} results",
            results.len()
        );

        // Get final stats from context
        let stats = context.stats();

        let mut all_files: Vec<String> = Vec::new();
        let mut total_turns = 0;
        let mut total_duration_ms = 0u64;
        let mut errors: Vec<String> = Vec::new();
        let mut degradations: Vec<String> = Vec::new();
        let mut cancellations: Vec<String> = Vec::new();
        let mut builders = Vec::new();
        let mut background_processes = Vec::new();

        for result in &results {
            builders.push(result.evidence_json());
            background_processes.extend(result.background_processes.iter().cloned());

            if is_cancelled_build_result(result) {
                cancellations.push(format!("{}: cancelled", result.task_id));
            } else if is_degraded_build_result(result) {
                degradations.push(format!("{}: {}", result.task_id, result.outcome_reason()));
            } else if !is_complete_build_result(result) {
                errors.push(format!(
                    "{}: {}",
                    result.task_id,
                    result.error.as_deref().unwrap_or(result.outcome_reason())
                ));
            }

            all_files.extend(result.files_examined.clone());
            total_turns += result.turns_used;
            total_duration_ms += result.duration_ms;
        }
        deduplicate_background_processes(&mut background_processes);

        let mut unique_files = Vec::new();
        for file in all_files {
            if !unique_files.iter().any(|existing| existing == &file) {
                unique_files.push(file);
            }
        }

        let message = format!(
            "Build completed: {} builders, {} turns, +{} -{} lines across {} files",
            results.len(),
            total_turns,
            stats.lines_added,
            stats.lines_removed,
            stats.files_modified,
        );
        let counts = build_result_counts(&results);
        let incomplete_builders = counts
            .degraded
            .saturating_add(counts.cancelled)
            .saturating_add(counts.failed);
        let process_handoff = active_process_handoff_summary(&background_processes);
        let outcome = if counts.cancelled > 0 {
            "cancelled"
        } else {
            classify_build_outcome_with_handoff(
                results.len(),
                incomplete_builders,
                stats.files_modified,
                process_handoff.is_some(),
            )
        };
        let confidence = build_confidence_with_handoff(
            incomplete_builders,
            stats.files_modified,
            process_handoff.is_some(),
        );
        let outcome_reason = if counts.cancelled > 0 {
            "cancelled"
        } else if stats.files_modified > 0 {
            if incomplete_builders == 0 {
                "file_modifications"
            } else {
                "mixed"
            }
        } else if process_handoff.is_some() && incomplete_builders == 0 {
            "active_process_handoff_readiness_unverified"
        } else if process_handoff.is_some() {
            "partial_process_handoff"
        } else {
            "no_usable_evidence"
        };
        let investigation_summary = build_summary_with_handoff(
            counts.complete,
            counts.degraded,
            counts.cancelled,
            counts.failed,
            stats.files_modified,
            stats.lines_added,
            stats.lines_removed,
            process_handoff.as_deref(),
        );
        let coverage_issues = errors
            .iter()
            .chain(degradations.iter())
            .chain(cancellations.iter())
            .cloned()
            .collect::<Vec<_>>();
        let coverage_gap_notice = build_coverage_gap_notice(&coverage_issues);

        let high_contention_files = stats
            .high_contention_files
            .iter()
            .map(|(path, duration)| {
                json!({
                    "file": path.display().to_string(),
                    "wait_secs": duration.as_secs_f64(),
                })
            })
            .collect::<Vec<_>>();

        let payload = json!({
            "delegated_run_id": delegated_run_id,
            "message": message,
            "investigation_summary": investigation_summary,
            "confidence": confidence,
            "outcome": outcome,
            "outcome_reason": outcome_reason,
            "builder_count": results.len(),
            "agent_count": results.len(),
            "successful_agents": counts.complete,
            "usable_agents": counts.usable,
            "degraded_agents": counts.degraded,
            "cancelled_agents": counts.cancelled,
            "failed_agents": counts.failed,
            "total_turns": total_turns,
            "total_duration_ms": total_duration_ms,
            "paths_examined": unique_files,
            "paths_examined_count": unique_files.len(),
            "files_examined": unique_files,
            "builders": builders,
            "background_processes": background_processes,
            "lines_added": stats.lines_added,
            "lines_removed": stats.lines_removed,
            "files_modified": stats.files_modified,
            "lock_contentions": stats.lock_contentions,
            "total_lock_wait_ms": stats.total_lock_wait_ms,
            "high_contention_files": high_contention_files,
            "coverage_gap_notice": coverage_gap_notice,
            "degradations": degradations,
            "cancellations": cancellations,
            "errors": errors,
            "delegation_policy": delegation_policy.audit_json(),
        });

        if durable_run_started {
            let lease = delegated_lease
                .as_mut()
                .expect("durable build start has an open store");
            let final_stage = match outcome {
                "success" => DelegatedRunStage::Complete,
                "partial" => DelegatedRunStage::Degraded,
                "cancelled" => DelegatedRunStage::Cancelled,
                _ => DelegatedRunStage::Failed,
            };
            let authoritative = match persist_delegated_artifact(
                lease,
                &delegated_run_id,
                final_stage,
                &payload,
                &investigation_summary,
                true,
            ) {
                Ok(authoritative) => authoritative,
                Err(error) => {
                    return delegated_persistence_error(&delegated_run_id, payload, &error);
                }
            };
            lease.disarm(&delegated_run_id);
            if let Some(synthesis_permit) = synthesis_permit {
                if let Err(error) =
                    synthesis_permit.finalize(group_terminal_state(authoritative.stage))
                {
                    return delegated_persistence_error(&delegated_run_id, payload, &error);
                }
            }
            // Individual builders finish before the aggregate artifact does.
            // Re-emit one authoritative aggregate boundary after persistence
            // so the foreground card cannot be stranded in Running.
            if let Some(ref tx) = ctx.agent_progress_tx {
                let (status, current_action) =
                    agent_progress_for_terminal_stage(authoritative.stage);
                let _ = tx.send(AgentProgress {
                    delegated_run_id: Some(delegated_run_id.clone()),
                    task_id: parent_name.to_string(),
                    name: parent_name.to_string(),
                    identity: None,
                    status,
                    tool_count: 0,
                    tokens: 0,
                    current_action,
                    completion_summary: Some(
                        authoritative
                            .human_review
                            .unwrap_or_else(|| investigation_summary.clone()),
                    ),
                    lines_added: stats.lines_added,
                    lines_removed: stats.lines_removed,
                    completed_plan_task: None,
                });
            }
        }

        let warnings = if durable_run_started {
            Vec::new()
        } else {
            vec![
                "This synchronous delegated build ran without a durable delegated-run record."
                    .to_string(),
            ]
        };
        ToolResult::success_data_with(payload, warnings, None, None)
    }
}

fn group_terminal_state(stage: DelegatedRunStage) -> crate::storage::DelegationGroupState {
    match stage {
        DelegatedRunStage::Complete => crate::storage::DelegationGroupState::Complete,
        DelegatedRunStage::Degraded => crate::storage::DelegationGroupState::Degraded,
        DelegatedRunStage::Failed => crate::storage::DelegationGroupState::Failed,
        DelegatedRunStage::Cancelled => crate::storage::DelegationGroupState::Cancelled,
        DelegatedRunStage::Created
        | DelegatedRunStage::Running
        | DelegatedRunStage::Synthesizing => crate::storage::DelegationGroupState::Failed,
    }
}

#[cfg(all(test, unix))]
mod tests {
    use std::time::Duration;

    use crate::agent::subagent::{
        DelegatedEvidenceKind, DelegatedEvidenceSummary, DelegatedProcessArtifact, SubAgentResult,
        SubAgentTermination,
    };
    use crate::process::ProcessRegistry;

    use super::{
        active_process_handoff_summary, build_confidence_with_handoff, build_result_counts,
        classify_build_outcome_with_handoff, revalidate_background_processes, BuildResultCounts,
    };

    fn result_with_termination(
        id: &str,
        termination: SubAgentTermination,
        success: bool,
        with_evidence: bool,
    ) -> SubAgentResult {
        let mut evidence = DelegatedEvidenceSummary::default();
        if with_evidence {
            evidence.record_attempt();
            evidence.record_success(DelegatedEvidenceKind::Mutation);
        }
        SubAgentResult {
            task_id: id.to_string(),
            agent_name: id.to_string(),
            delegated_run_id: Some("run-build-counts".to_string()),
            success,
            output: format!("{id} result"),
            files_examined: if with_evidence {
                vec![format!("{id}.rs")]
            } else {
                Vec::new()
            },
            duration_ms: 1,
            turns_used: 1,
            error: if termination == SubAgentTermination::Completed {
                None
            } else {
                Some(format!("{termination:?}"))
            },
            termination,
            policy_violations: Vec::new(),
            evidence,
            background_processes: Vec::new(),
        }
    }

    #[test]
    fn aggregate_counts_distinguish_complete_degraded_cancelled_and_failed_results() {
        let results = vec![
            result_with_termination("complete", SubAgentTermination::Completed, true, true),
            result_with_termination(
                "interrupted",
                SubAgentTermination::ProviderTimeout,
                false,
                true,
            ),
            result_with_termination("loop-guarded", SubAgentTermination::LoopGuard, false, true),
            result_with_termination("failed", SubAgentTermination::Failed, false, false),
            result_with_termination("cancelled", SubAgentTermination::Cancelled, false, true),
            // A model success label without usable evidence is not completion proof.
            result_with_termination("unproven", SubAgentTermination::Completed, true, false),
        ];

        assert_eq!(
            build_result_counts(&results),
            BuildResultCounts {
                complete: 1,
                degraded: 2,
                cancelled: 1,
                usable: 3,
                failed: 2,
            }
        );
        assert_eq!(
            classify_build_outcome_with_handoff(3, 1, 0, true),
            "partial"
        );
    }

    fn captured_process(process_id: &str, endpoint_hints: Vec<String>) -> DelegatedProcessArtifact {
        DelegatedProcessArtifact {
            process_id: process_id.to_string(),
            status: "running".to_string(),
            command: "captured startup command".to_string(),
            working_dir: "/tmp".to_string(),
            endpoint_hints,
            reused_existing: false,
        }
    }

    async fn wait_until_terminal(registry: &ProcessRegistry, owner_id: &str, process_id: &str) {
        tokio::time::timeout(Duration::from_secs(2), async {
            loop {
                if registry
                    .get_for_user(owner_id, process_id)
                    .await
                    .is_some_and(|process| !process.is_active())
                {
                    return;
                }
                tokio::time::sleep(Duration::from_millis(10)).await;
            }
        })
        .await
        .expect("tracked process should reach a terminal state");
    }

    #[tokio::test]
    async fn process_that_dies_before_aggregation_is_not_an_active_handoff() {
        let temp = tempfile::tempdir().expect("tempdir");
        let registry = ProcessRegistry::new();
        let owner_id = "owner-a";
        let process_id = registry
            .spawn_for_user(
                owner_id,
                "exit 0".to_string(),
                temp.path().to_path_buf(),
                None,
                None,
            )
            .await
            .expect("spawn short process");
        wait_until_terminal(&registry, owner_id, &process_id).await;

        // Model the earlier Bash startup artifact, which may still say
        // `running` even though the registry monitor has observed completion.
        let mut processes = vec![captured_process(
            &process_id,
            vec!["127.0.0.1:5940".to_string()],
        )];
        revalidate_background_processes(&mut processes, Some(&registry), Some(owner_id)).await;

        assert_eq!(processes[0].status, "done");
        assert!(active_process_handoff_summary(&processes).is_none());
        assert_eq!(
            classify_build_outcome_with_handoff(1, 0, 0, false),
            "failed"
        );
        assert_eq!(build_confidence_with_handoff(0, 0, false), "low");
    }

    #[tokio::test]
    async fn non_endpoint_process_only_handoff_is_not_usable_build_evidence() {
        let temp = tempfile::tempdir().expect("tempdir");
        let registry = ProcessRegistry::new();
        let owner_id = "owner-a";
        let process_id = registry
            .spawn_for_user(
                owner_id,
                "sleep 5".to_string(),
                temp.path().to_path_buf(),
                None,
                None,
            )
            .await
            .expect("spawn sleep process");
        let mut processes = vec![captured_process(&process_id, Vec::new())];

        revalidate_background_processes(&mut processes, Some(&registry), Some(owner_id)).await;
        let has_handoff = active_process_handoff_summary(&processes).is_some();

        assert!(!has_handoff);
        assert_eq!(
            classify_build_outcome_with_handoff(1, 0, 0, has_handoff),
            "failed"
        );
        assert_eq!(build_confidence_with_handoff(0, 0, has_handoff), "low");

        registry
            .kill_for_user(owner_id, &process_id)
            .await
            .expect("kill sleep process");
    }

    #[tokio::test]
    async fn active_handoff_is_owner_scoped_and_does_not_downgrade_file_evidence() {
        let temp = tempfile::tempdir().expect("tempdir");
        let registry = ProcessRegistry::new();
        let owner_id = "owner-a";
        let process_id = registry
            .spawn_for_user(
                owner_id,
                "sleep 5".to_string(),
                temp.path().to_path_buf(),
                None,
                None,
            )
            .await
            .expect("spawn tracked process");
        let mut owned = vec![captured_process(
            &process_id,
            vec!["127.0.0.1:5940".to_string()],
        )];

        revalidate_background_processes(&mut owned, Some(&registry), Some(owner_id)).await;
        assert_eq!(owned[0].status, "running");
        assert!(active_process_handoff_summary(&owned)
            .is_some_and(|summary| summary.contains("127.0.0.1:5940")));

        let mut other_owner = owned.clone();
        revalidate_background_processes(&mut other_owner, Some(&registry), Some("owner-b")).await;
        assert_eq!(other_owner[0].status, "missing");
        assert!(active_process_handoff_summary(&other_owner).is_none());

        // Existing file-modifying build evidence remains the basis for the
        // normal high-confidence classification; process readiness is not.
        assert_eq!(
            classify_build_outcome_with_handoff(1, 0, 2, true),
            "success"
        );
        assert_eq!(build_confidence_with_handoff(0, 2, true), "high");

        registry
            .kill_for_user(owner_id, &process_id)
            .await
            .expect("kill tracked process");
    }
}
