import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const websiteRoot = resolve(scriptDir, "..");
const repoRoot = resolve(websiteRoot, "../..");
const sourcePath = resolve(repoRoot, "docs/extensions/catalog.json");
const staticTarget = resolve(websiteRoot, "static/plugin-catalog.json");
const generatedTarget = resolve(
	websiteRoot,
	"src/lib/data/catalog.generated.ts",
);

const raw = readFileSync(sourcePath, "utf8");
const catalog = JSON.parse(raw);

mkdirSync(dirname(staticTarget), { recursive: true });
mkdirSync(dirname(generatedTarget), { recursive: true });
writeFileSync(staticTarget, `${JSON.stringify(catalog, null, 2)}\n`);
writeFileSync(
	generatedTarget,
	`// Generated by scripts/sync-plugin-catalog.ts. Do not edit by hand.\nexport const catalog = ${JSON.stringify(catalog, null, 2)} as const;\n`,
);

console.log(`synced ${catalog.plugins?.length ?? 0} plugin catalog entries`);
